#!/bin/bash

current_dir=$(pwd)
if [[ $# -eq 2 ]]; then
    java -cp /usr/local/src/notes2latex Notes2Latex $current_dir/$1 > $current_dir/$2 || exit 1
elif [[ $# -eq 1 ]]; then
    java -cp /usr/local/src/notes2latex Notes2Latex $current_dir/$1 || exit 1
else
    echo "usage: notes2latex <file_name> [<output_name>]"
    exit 2
fi


